# -*- coding: utf-8 -*-
"""01 - Python Fundamentals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14IuThJPZ141TLiUqfgQuCPYjChJclVO0

# Print Functionality
"""

print('Hello world')

print("K k menon")

print(salman khan)

print(7)

print(7.7)

print(True)

print('Hello',2,4.4,True)

print('Hello',2,4.4,True,sep='/')

print('Hello',2,4.4,True,sep=' ')

print('hello',end=' ')
print('World')

print('hello')
print('World')



"""# Data Types(Dtypes)"""

# Integer
print(8)

#Float/Decimal
print(8.8)

#String/Text
print("Hello World")

#Boolean
print(True)
print(False)

#Complex
print(3+4j)

#List
print([1,2,3,4,5])

#Tuple
print((1,2,3,4,5))

#Sets
print({1,2,3,4,5})

#Dictionary
print({'name':'Rajvardhan','Gender':'Male'})

#type Function -> Tells datatype of any data
type(8)

type("Helo")

type({1,2,3})

type(3+4j)

"""# Varaibles"""

name = "Raj"
print(name)

name =5
print(name)

#dynamic typing
value = 50000

#Static typing
int value = 50000

#Dynamic binding
name = 5
print(name)
name = "Rajvardhan"
print(name)

#Static binding
int c = 10
int c = "Raj"

#stylish techniques of varaible declaring
#normal
a = 4
b=5
c=6
print(a+b+c)
print(a,b,c)

a,b,c = 1,2,3
print(a,b,c)

a=b=c=5
print(a,b,c)

# Commnets
#This is commnt
#This is single line commnet



"""# Keywords and Identifiers"""

#Keywords are reserved words
#python uses interpretor.
#Interpretor = high level language to low leval language(binary)
#Keyword don't used as normal words.

#identifiers = Names [varaible,function,class]
#1} Can't start with digit
#2]Can't use keyword
#3]Special character only '_' (underscore) is allowed

# All allowed ->name ,first_name , _, name1_king
# Not aloowed -> 1name

"""## Input Function"""

input()

input("Enter your name ")

# Static vs Dynamic software
# Static = no user input -> ex]calender,clock,blog -> 1% softwares of the world
#Dynamic = user input -> ex] Zomato,Youtube , Chrome ->99% of world sofwares are dynamic

#Getting inputs from user
first = input('Enter first number ')
second = input('Enter second number ')
#Addting both inputs and store in varaible
sum = (first) + (second) ## it is type casting.
#display result
print(sum)

# why ans is like 1020
# beacause python by deafult take input as "String"
# why string = String is universal fomat , you can store any other type of data in string

#Getting inputs from user
first = input('Enter first number ')
second = input('Enter second number ')
#Addting both inputs and store in varaible
sum = int(first) + int(second) ## it is type casting.
#display result
print(sum)

#Getting inputs from user
first = int(input('Enter first number ')) # This will change the datatype becaz you are storing the variable with converted datatype
second = int(input('Enter second number '))
#Addting both inputs and store in varaible
sum = int(first) + int(second)
#display result
print(sum)
type(first)

"""## Type conversion"""

#Implicit and explicit
#Type conversion -> From one data type to another

#Implicit
#Python by itself do conversion
print(5 + 5.6)

print(type(5),type(5.6))

print(4 +'4')

#Explicit
#We told pyhon to please change dtype

# str -> int
type(int('4'))

# int -> str
type(str(4))

# before doing explicit convertion think about it is possible or not
# complex -> int

int((4+5j))

## Python interview aspect:
# Python type conversion dont make any changes in original data it create completely new object in memory and we perform operations on it
#You may give the code snippet and ask about output

"""## **Literal**"""

# Literal = value of varaible
# sum = 15 -> sum is varaible, = is operator , 15 is literal ,dtype is data type of literal
#1]
# INT LITERAL
a = 0b1010 # Binary literal. Represented using 0b at begining
b = 1010 # Decimal(normal) literal.
c = 0o1010 # Octal literal. Represented using 0o at begining
d = 0x1010 # Hexadecimal literal. Represented using 0x at begining

print(a,b,c,d,sep='\n')

#2]FLOAT LITERAL
float_1 = 23.45 # Manually defining literal
float_2 = 1.5e3 #scientifically defiend(positive) -> 1.5e2= 1.5*10^2
float_3 = 1.5e-3 #scientifically defiend(Negative) -> 1.5e2= 1.5*10^-3

print(float_1,float_2,float_3)

#3]COMPLEX LITERAL
comp = 4+5j
comp2 = 4.5j

print(comp.real,comp.imag,sep=',')

#3]STRING LITERAL
a = 'This is python'
b = "This is python"
c = """This is also string """
d = u'\U0001f600'
e = r'\n,\t these all are raw strings'

print(a,b,c,d,e,sep='\n')

#4]BOOLEAN LITERAL
#Python treats boolean exp's as the numbers in mathematical exp's -> thismay be asked in interviws as code snippet
A = True + 4
B = False + 20
print(A,B,sep='\n')

"""None"""

#Used to decleare varaible in python
#As we know we cant declare varaible initially in python so assign value 'None ' is a way to decleare a varaible.

aman = None
b = 40
c = 80
print(b+c)

aman = None
print(aman)

