# -*- coding: utf-8 -*-
"""02 - Python conditionals,Loops,Operators.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UGZXmFiCCqXRQ7wRUr9dN5EQJ3qtuA_F

# Operators
"""

# 1] Arithemetic Operators

#used for mathematical operation
print(4 + 5)
print(4 - 5)
print(4 * 5)
print(4 / 5)
print(4 // 5) #integer division -> converts result of division into integer
print(42 % 5)
print(2**3) # power operator

# 2] Relational Operators

#also called as comparision operators
print(4 > 5)
print(4 < 5)
print(4 >= 5)
print(4 <= 5)
print(4 == 4)
print(4 != 4)

# 3] Logical Operators

# used for logic building and condition checking
print (1 and 0)

print(1 or 0)

print(not 1)

# 4] Bitwise Operatoes

# -> works on binary numbers

#1)Bitwise and
print(2 & 3)

#2)Bitwise or
print(2 | 3)

#3)Bitwise xor
print(2 ^ 3)

#4)Bitwise not
print(~3)

#5)Bitwise leftshift
print(4 >> 2)

#6)Bitwise rightshift
print(4 << 2)

# 5] Assignment Operator

a = 2 # = is assignment operator -> used to assign values
print(a)

#Assignment operator uses with many arithematic operator

a += 2
print(a)

a -= 2
print(a)

a *= 2
print(a)

a /= 2
print(a)

a %= 2
print(a)

# 6] Membership Operator

# in / not in  -> works on string,list,tuple,dictionary,set.

print('D' in 'Delhi')

print(2 not in [3,4,5])

a = "Raj"

a += "vardhan"

print(a)

#Q] find the sum of 3 digit number entered by user

num = int(input("Enter the number "))

a =  num % 10

num = num // 10

b = num % 10

num = num // 10

#c = num
c = num % 10

print(a + b + c)

"""# Conditionals"""

# If - else statement:

# if there is branching in code then we use if-else to handle it
#python indentation = spacing concept
#python's core pholosophy is that code must be readable and look beautiful that's why it don't contain any semicolon and bracket(curley braces) it uses indentation
#normal spacing se extra spacing = indentation

# Login program

email = input("Enter email")
password = input("Enter password")
if (email == "rajvardhan@gmail.com") and (password == "1234"):
  print("Welcome")
else:
  print("Invalid password or email")

#if there are two conditions use if-else
#if more than two conditions use if-elif-else
#you can also use nestef if-else means you can write if-else inside the another if-else or only if or only else.

email = input("Enter email ")
password = input("Enter password ")

if (email == "raj@gmail.com") and (password=="123"):
  print("welcome")
elif (email == "raj@gmail.com") and (password != "123"):
  print("incorrect password")
  password = input("Enter password again ")
  if (password == '123'):
    print('welcome !finallyy')
  else :
    print("beta , tumse na ho payega!")
else :
  print("incorrect email or password ! plese check again")

# 1] Find min number among 3
a = int(input("Enter first number "))
b = int(input("Enter second number "))
c = int(input("Enter third number "))
13
if (a<b) and (a<c):
  print("A is smallest")

elif (b<a) and (b<c):
  print("B is smallest")

else:
  print("C is smallest")

a = int(input("Enter first number "))
b = int(input("Enter second number "))
c = int(input("Enter third number "))

if (a<b) and (a<c):
  print("A is smallest")

elif (b<c):
  print("B is smallest")

else:
  print("C is smallest")

23# 1] Find max number among 3
a = int(input("Enter first number "))
b = int(input("Enter second number "))
c = int(input("Enter third number "))

if (a>b) and (a>c):
  print("A is largest")

elif (b>a) and (b>c):
  print("B is largest")

elif(c>a) and (c>b):
  print("C is largest")

else:
  print("Plese enter valid choice")

# 2] menu driven program

fnum = int(input("Enter first number "))
snum = int(input("Enter second number "))

op = input("Enter the opration.choices must among +,-,*,/,% ")

if (op == '+'):
  print(fnum + snum)

elif (op == '-'):
  print(fnum - snum)

elif (op == '*'):
  print(fnum * snum)

elif (op == '/'):
  print(fnum / snum)

elif (op == '%'):
  print(fnum % snum)

else:
  print("Enter valid choice mitra")

##  triple double inverted comma used to write multiline string

"""# Modules"""

# modules are using others code in our code
# increase code reusability
#similar as #include<stdio.h> in c and #include<iostream> in c++

# math module
# -> All mathematical functions are included
import math

math.factorial(5)

# keyword module
# -> shows list of all python keywords
import keyword
keyword.kwlist

# random module
# -> used to genrate random numbers

import random

print(random.randint(1,100000))

# datetime module
# -> can tell current date and time

import datetime
datetime.datetime.now()

from datetime import datetime

now = datetime.now()
print("Current Date & Time:", now)

from datetime import datetime
import pytz

india_timezone = pytz.timezone("Asia/Kolkata")
india_time = datetime.now(india_timezone)

print("Current time in India:", india_time.strftime("%Y-%m-%d %H:%M:%S"))

# HOW TO SEE ALL MODULES IN PYTHON OR CHECK HOW MANY MODULES IN PYTHON
help('modules')

import sys
print(sys.builtin_module_names)

"""# Loops"""

# Loops are used to perform same thing repeteatively
# loops are used in website building ex] flipcart result display it shows all results in same structure
# use python tutor if you find any difficulty in code

# python has two types of loop
# 1.while loop
# 2.for loop

#while loop
#print table of user inputed number

number = int(input("Enter the value of number "))

i=1;

while (i<=10):
  print(number,"*",i,"=",number*i)
  i=i+1

# while loop with else statement

i=1

while(i<3):
  print(i)
  i+=1
else:
  print("loop ended")

#Guessing game

import random
jackpot = random.randint(1,100)

guess = int(input("Guess the number "))
counter = 1

while (guess != jackpot):
  if guess < jackpot :
    print("Galat ! guess higher")

  else :
    print("Galat ! guess lower")

  guess = int(input("guess again "))
  counter += 1

else:
  print("You guessed right.","It is ",jackpot)

# 2] for loop

# more flexible and more powerful
# more easy
# don't need to specify starting or ending number or incrementation
# you can run it through list,tuple,string,dictionary,set,and range function

for i in range(1,11):
  print(i)

for i in range(1,11,2):
  print(i)

for i in "Rajvardhan":
  print(i)

for i in [1,2,3,4,5]:
  print(i)

# ex]

# current population = 10000
# increases 10% each year
# calculate for last 10 year

curr_pop = 10000

for i in range(10,0,-1):
  print(i,curr_pop)
  curr_pop = curr_pop - 0.1*curr_pop

current = 10000

for i in range(1,11):
  print(current)
  current = current - 0.1*current

