# -*- coding: utf-8 -*-
"""03 - Strings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lBZ7r0tQ7zpoCqv0AUthYFDUHGpuJcq9

# Remaining loops
"""

# population wala wuetion
curr_pop = 10000
i = 1

for i in range(10,0,-1):
  print(i,curr_pop)
  curr_pop=curr_pop/1.1
  #logic
  # 9th year = x , to 10 th year me means current year me population 10000 chahiye aur population har saal 10% se badhta hain.To 9th year uskar 10 % jod dnege to 10000 aana chahiye
  #mathematically x + 10%x = 10000 -> x + 0.1x = 10000 -> 1.1x = 10000 -> x = 10000/1.1
  # galati kaha huyi = hame current year me se uska 10% minus kiya (hame 10 se 1 tak gaye ) par hame (1 se 10 tak aana tha)

# Q] 1/1! + 2/2! + 3/3!....n
# sirji ka logic
num = int(input("Enter the number "))
fact = 1
result = 0
for i in range(1,num+1): # (first , last) first wala include hota hain , last wala excluded hota hain
  fact = fact*i
  result = result + i/fact
print(result)

# Q] 1/1! + 2/2! + 3/3!....n
# my own logic

num = int(input("Enter the number "))

import math
result = 0
for i in range(1,num+1): # (first , last) first wala include hota hain , last wala excluded hota hain

  result = result + i/math.factorial(i)

print(result)



# Netsed Loops

for i in range(1,5):
  for j in range(1,5):
    if(i!=j): # to make oly unique pairs like (a,b) avoid (a,a)
      print(i,j)

# Q]   *        print this pattern
    #  **
    #  ***
    #  ****
    #  *****


row = int(input("enter rows "))

for i in range(1,row+1):
  for j in range(1,i+1):
    print("*",end='')
  print()

# Q] 1    print this pattern
#    121
#    12321
#    1234321


row = int(input("Enter rows "))

for i in range(1,row+1):
  for j in range(1,i+1):
    print(j,end='')
  for k in range(i-1,0,-1):
    print(k,end='')
  print()



"""## Loop control statements"""

#1]break
#it is used to break the flow of loop as per written condition -> uske baad ka sara code execute hi nahi hoga -> loop me se bahar chale jaoge
# real life example -> you are searching for your prn in merit list through loop when you get it you dont check further

for i in range(1,11):
  if i == 15:
    break
  print(i)

from typing import Counter
# Q] Find numbers between range given by user

low_range = int(input("Enter lower range "))
upper_range = int(input("Enter upper range "))
count = 0

for i in range(low_range,upper_range+1):
  if i==1:
    continue

  for j in range(2,i):
    if i%j == 0:
      break
  else:
    count+=1
    print(i)

print("Count of rime no's between",low_range,"and",upper_range,"is",count)

#2]continue
# us particular iteratio ke liye niche ka code skip karat hain

#ex]

for i in range(1,11):
  if i == 6:
    break
  else:
    print(i)

#3]pass
#used to save from error
# aap ek piece of code ko include karna chahte ho but aapko logic pata nahi hain ya yaad nahi aa raha to aap interpreter ko bata rahe ho ki bas is code ko enecute karo
#

for i in range(1,100):
  pass



"""# Strings"""

# strings = collection of characters
# official defination : Sequence of unicode characters
# kisi bhi text ko programming me strings bola jata hain

"""### Creating strings:"""

#]


s = 'Hello'       # used when there is double inverted comma in string then we include that all string in single inverted so interpreter do not get confused ex] s = 'Hii,"I am raj"'
                    #s = 'Heelo,"I am cr7"'
s="Hello"            # when we have to use single inverted comma in string then we include that whole string in double inverted comma. ex] s = " helo I'm rajvardhan"
                       # s = " helo I'm rajvardhan"
s = '''hello'''
s = """Helo"""
s = str('abc')
print(s)

"""### indexing:"""

#]


# extracting any character grom string known as indexing

#Positive indexing:
s = "Rajraj chola 1"
s[5]

#Negative Indexing:
s1 = "rajendra Chola"
s1[-1]
# it is used when we don't know about len of string in that case we use it

"""### Slicing"""

#]


# extracting one character = indexing
# extracting more than oe character(substring) = slicing

#Positive Slicicng
s = "Hello World"
s[0:6]
s[4:5]
s[0:]
s[:6]
s[:]
s[0:4:2]

#Negative Slicing: always remeber Larger number at starting
s[-6:]
s[-1:]
s[:-9]

#code to reverse string
s= "bavuma"
s[::-1]

"""### Editing and Deleting:"""

#]

#Python strings are immutable(You can't change the string sfter it's creation)

s = 'Kaise ho'
s[1]='A'

#you can delete string
s="kingmen"
del s
print(s)

"""### Operations:"""

#1]Arithematic Operator:
print('Raj'+'vardhan')

print('Rajvardhan '*10)

#2]Relational

'Delhi' == 'Delhi'

'Delhi' == 'Munbai'

'Delhi' != 'Delhi'

'pune' >= 'Delhi' # Baes on ascii value (Lexiograhically)

'pune' <= 'Delhi'

'pune' > 'mumbai'

'pune' < 'mumbai'





#3]Logical Operators

'delhi' and 'mumbai'

'delhi' or 'mumbai'

'' and 'king' # empty string = false, # filled string = True
              # in case of or as we enter first string it gets true thats why it print first string
              #in case of and, as we enter second string it checks it is  true or not  thats why it print second string

'' or 'king'





#4]Loops in string

for i in 'Kolkata':
  print(i)

for i in 'Chandigrah':
  print('Pune')





#5]membership operator

'd' in 'delhi'

'm' not in 'katak'



"""### List Functions"""

# Coomon Functions : applicable on all data types -> string,list,tuple,set,dictionary
# special functions : individually different



len('Rajvardhan')

max('rajvardhan') # based  on ascii value

min('Rajvardhan')

sorted('Rajvardhan')  # Ascending order

sorted('Rajvardhan',reverse=True)  # Descending order

sum('Rajvardhan') # yaha work nahi karta.Assumption:all memebrs are int or float

# Special Functions
# Group 1

s = 'rajvardhan Shewale'

s.capitalize() # Makes first letter of sentence capital

s.title() # Makes first letter of each word of sentence capital

s.upper() # make all lates uppecase

s.lower() # makes all letters lowecase

s.swapcase() # make all captital letters to small and all small to capital





# Group 2

s.count('a') # particular letter us string me kitni bar aaya hain ye count karta hain

s.find('var') # Finds index of substring in that main string

s.find('x')

s.index('var') # same function as find() , but when we search for a substring that does not exist it gives error while find() print -1





# Group 3

sr = 'Kingsmen2345'

sr.endswith('le')

sr.startswith('K') # asks does string ennds with given/passed substring

sr.startswith('kin')  # asks does string starts with given/passed substring





# Group 4

sr.isalnum() # checks is string contain alphabates or numbers if yes ans is true and other than aplhabates or numbers ans is no

sr.isalpha() # checks is string contain only alphabates .if yes ans is true and other than aplhabates ans is no

srp= '123a'

srp.isnumeric() # checks is string contain only numbers .if yes ans is true and other than numbers ans is no

srp.isdigit() # Same working as isnumeric()

srp.isidentifier() # checks for is it valid for identifier





# Group 4

a = 'Raj'
b = 'Male'

'Hello,my name is {} and i am {}'.format('Raj','Male') # format() is used to insert substring in defined string

'Hello,my name is {0} and i am {1}'.format('Raj','Male')

'Hello,my name is {1} and i am {0}'.format('Male','Raj')





# Group 5

"Hi I am Rajvardhan Shewale ".split() # Break sentence into words using sep = ' '. You can change it

"Hi I am Rajvardhan Shewale ".split('a')

" ".join(['Hi', 'I', 'am', 'Rajvardhan', 'Shewale']) # joins words in list by using ' ' by default.Exact opposite of split().You can change it.

"-".join(['Hi', 'I', 'am', 'Rajvardhan', 'Shewale'])





# Group 6

'Hi I am Rajvardhan Shewale'.replace('Rajvardhan','Ranveer') # replace thar sustring with new word.If that substring is wrong retain original string

'Hi I am Rajvardhan Shewale'.replace('Rajvardhan1','Ranveer')

"        Raj              ".strip() # removes extra spaces before and after string.Do not removes spcaes in between words.used in databases

"Raj shewale"

