# -*- coding: utf-8 -*-
"""04 - List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q-eRir2rdOnMRPfP5NA5vME_d9Imlmu1

# List

## Basic
"""

# lists are dynamic array.ex ] l1 = [1 , [2,3] , 3+6j , 4.4 , 'Raj']
# when you have so many things and you want to store it , insted of asaign each to each varaible you use list in which you put all them together
# why list are used or required:
# store multiple things in one place.
# ex] you have to perform some operation on all things in list ,you can easily do through loop.But if each thing is seprate varaible then you have to do it for each one whch is hectic

# Array  vs List
#1.fixed size vs dynamic size
#2.homogenuous(only 1 datatype) vs hetrigenous (store all data types)
#3.speed(array) > speed(list)
#4.memory(array) > memory(list) -> memory me space

#
l = [1,2,3]
print(id(l))

print(id(l[0])),print(id(1))

print(id(l[1])),print(id(2))

print(id(l[2]))



"""## Charecteristics"""

#1 ]Ordered : Order of items matter.
l = [1,2,3]
l2 = [3,2,1]
l == l2

#2] Hetrogenous : Store multiple types of object
l3 = [1,2.2,'ram']

#3] Dynamic : Size is not fixed,you can add multiple item as you want

#4] Mutable/Changable : You can edit or change the list unlike String which is immutable

#5] Duplicated allowed :
l4 = [1,2,3,2,1,]

#6] Can be nested:
l5 = [1,2,[3,'king',[4,5]]]

#7] Items can be accesed
l5 = [1,2,3]
l5[0]

#8] Can store any kind of object in python
print([1,2,3,print,input,list])

"""## Creating List"""

#Empty
print([])

#1D
print([1,2,3])

#2D  -> list inside list
print([1,2,3,[1,2,3]])

#3D -> list inside list which is inside another list.Jitne brackets (left side) khule utne dimension ka list
print([[[1,2,3],[2.3,3.4,5.4]],[[1,2,3],[4,5,6]]])

#type conversion
print(list('Hello'))

#hetrogenous
print([1,2.2,3+4j,True,'list',[1,2,3]])

"""## Accesing items from list

### Indexing
"""

#Positive   -> left to right,strats from 0
l = [1,2,3,4]
print(l[0])
print(l[2])
# print(l[23])

#Negative  -> right to left,starts from -1
l=[1,2,3,4,5]
print(l[-1])
print(l[-4])

#Nested indexixng -> jitne dimension utne sqare brackets -> can do using negative indexing also
l = [1 , 2 , 3 , [1 , 2 , 3]]

print(l[3][1])

l1=[1,2,3,[1,2,4,[1,2,3,4,[3,4,5,[5,6,7,8,9]]]]]

l1[3]

l1[3][3]

l1[3][3][4]

l1[3][3][4][3]

l1[3][3][4][3][1]





"""### Slicing"""

l = [1,2,3,4,5,6,7,8,9] # same as string slicing

print(l[0:4])

print(l[0:])

print(l[:7])

print(l[:])

print(l[1:8:2])

print(l[::-2])

print(l[-7:-1])

print(l[-7:-1:2])# in negative jump should be positive

print(l[::-1])

print(l[-2:-6])

"""## Adding items to a list"""

#append() :add only one item at last. it Trys to add single item
l = [1,2,3,4,5]
l.append(7)
print(l)

l = [1,2,3,4,5]
l.append([8,9,6])
print(l)

l = [1,2,3,4,5]
l.append('raj')
print(l)



#extend() : add multiple items at last .it Trys to add multiple items

l = [1,2,3,4,5]
l.extend([6,7,8])
print(l)

l = [1,2,3,4,5]
l.extend([1,2,3,[4,5,6]])
print(l)

l = [1,2,3,4,5]
l.extend('delhi')
print(l)



#insert() : add one item at any place.insert(a,b) -> a = index at which you want to add items,b = the item which you want to add

l = [1,2,3,4]
l.insert(2,'raj')
print(l)

l = [1,2,3,4]
l.insert(2,100)
print(l)

""" ## Editing a List"""

l = [1,2,3,4,5]

#editing with indexing
l[1] = 200
print(l)

l[-1] = 500
print(l)

# editing with slicing

l[2:4] = [300,400]
print(l)

l[l[0],l[2]] = [1000,2000]
print(l)

"""## Deleing items from List"""

#del
l=[1,2,3,4,5]
print(l)

del l
print(l)

l=[1,2,3,4,5]

# through indexing
del l[0]
print(l)

# through slicing
del l[0:3]
print(l)

# remove() : delete item based on value means dont need index only give item value
l=[1,2,3,4,5,6]
l.remove(4)
print(l)

# pop() : delete item based on index(if index is provided) and if index is not provided delete last item
l=[1,2,3,4,5,6]
print(l)

l.pop()
print(l)

l.pop(2)
print(l)

l.pop(l[1]) # delete item after the item whcih index we provide
print(l)

#clear() : delete all items from list but don't delete list
l=[1,2,3,4,5,6]
l.clear()
print(l)

"""## Operations on list"""

# arithemetic

# addition : merges the list
l1 =[1,2,3]
l2 = [4,5,6]
print(l1+l2)

#multiplication:
l1 =[1,2,3]
print(l1*5)



# membership

l1 =[1,2,3]
print(3 in l1)
print(33 in l1)
print(33 not in l1)

#loop

for i in l1:
  for j in l2:
    print(i,j)

"""## List Functions"""

l = [1,2,3,4,5,9,6,4,0,2,7]

print(len(l))

print(min(l))

print(max(l))

print(sorted(l))

print(sum(l))

#count() : count the frequency of that number
l = [1,2,3,4,5,9,6,4,0,2,7]
l.count(2)

l.count(4)



#index() : Tells index of that item
l = [1,2,3,4,5,9,6,4,0,2,7]
l.index(5)



#reverse() : reverse the list permanatly
l = [1,2,3,4,5,9,6,4,0,2,7]
print(l)
l.reverse()
print(l)

print(l)



#sort() : sort the list permanatly
l = [1,2,3,4,5,9,6,4,0,2,7]
print(l)
l.sort()
print(l)

l.sort(reverse=True)
print(l)

print(l)



#copy() : create c copy of exixting list
l = [1,2,3,4,5,9,6,4,0,2,7]
print(l)
print(id(l))
l1 =l.copy()
print(l1)
print(id(l1))



"""## List comprehension"""



























"""## Traversing in list"""

# itemwise: avilable in only python

L = [1,2,3,4,5]

for i in L:
  print(i)

#indexwise : avilable on all languages

for i in range(0,len(L)):
  #print(i) # these are indexes
  print(L[i]) # this print items in list

"""## Zip() function"""

#

# write program to add items of two list based on index

l1 = [1,2,3,4]
l2 = [-1,-2,-3,-4]

list(zip(l1,l2))

[i+j for i,j in zip(l1,l2)]

print([1,2,3,print,type,input])

#everything in python is object and you can store any object in list

"""## Disadvantages"""

a = [1,2,3,4]
b=a.copy()
print(a)
print(b)

a.append(5)
print(a)
print(b)

print(id(a))
print(id(b))









