# -*- coding: utf-8 -*-
"""07_OOPs Part-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Tt17nux-XPyAutXyLikhvgLSTBGdC5Z

## Overview What is class and object
"""

print("Hello")

l = [1,2,3,4]
type(l)

l.upper()



"""## Class and object"""

#OOPs:
#Used to build Real world application
#Highly practical
#By using oops you can create your own data type

#Class:
#blueprint
#define rules how object will behave
#Don't take any space in memory
#Two types of class
#1]Built in classes : all datatypes like int float string tuple list
#2]user defined classes

#Object
#Instance of classs
#Can acsess all things of class



class Atm:

    #constructor
    def __init__(self):
        self.pin=''
        self.balance=0
        # print("Kya baat hain!")
        self.menu()

    def menu(self):
        user_input=input("""

        Enter Your Choice:
        1.Press 1 To Set New Pin
        2.Press 2 To Change Pin
        3.Press 3 To Check Balance
        4.Press 4 To Withdraw Cash
        5.Anything else to exit

        """)

        if(user_input == '1'):
            self.Create_pin()
            self.menu()

        elif(user_input == '2'):
            self.change_pin()
            self.menu()

        elif user_input == '3' :
            self.check_balance()
            self.menu()

        elif user_input == '4' :
            self.withdrawal()
            self.menu()

        else:
            False#To exit from loop you can use break






    def Create_pin(self):
        user_pin= input("Enter your pin")
        recheck_pin = input("Enter pin again")

        if (recheck_pin == user_pin):
            self.pin=user_pin
            print("Pin created succesfully")

            user_balance = int(input("Enter balance"))
            self.balance = user_balance
            print("Balance entered succesfully!")
        else:
            print("Pin is not created")




    def change_pin(self):
        if self.pin:
            old_pin = input("Enter your existing pin")
            if(old_pin == self.pin):
                new_pin = input("Enter new pin")
                self.pin = new_pin
                print("Pin changes Succesfully!")
            else:
                print("Nai karne de sakta re baba!")

        else:
             print("Beta pehle pin to banalo!")


    def check_balance(self):
        if self.pin:
            user_pins = input("Enter your pin")
            if (user_pins == self.pin):
                print("Your balance is :",self.balance)
            else:
                print("Nikal yaha se!")
        else:
            print("Beta pehle pin to banalo!")


    def withdrawal(self):
        if self.pin:
            user_pin = input("Enter pin")
            if user_pin == self.pin:
                amount = int(input("Enter the amount of withdrwal!"))
                if amount >= self.balance:
                    print("Abe garib!")
                else:
                    self.balance = self.balance-amount
                    print("Amount withdrwas succesfully!.Remaining amount = ",self.balance)
            else:
                print("Abe chor!")
        else:
            print("Pin to create karle beta!")

obj = Atm()
#objectName = Classname() ->Syntax to create objects



"""## constructor"""

#Constructor:
#1.It is special function -> it has superpower ->we dont need to call it explicitally -> it automatically calls when object is created



"""## method vs function"""

#Method vs Function:
#Method -> Function written inside class
#Function -> Function written outside the class

i = [1,2,3,4]
len(i) # len is function becaz it is outside the class
i.append(5) # append is method becaz it is inside the list class

i



"""## Magic methods"""

#Magic Methods:

# Magic methods -> special functions written inside class -> has superpower
# syntax : __init__(self) -> aage and piche double underscore laga hoga!

#Constructor:
#special method
#we dont need to call it explicitelt -> it activates or executes as we create object of class
# only single constructor
# name and syntax is fixed : __init__(self):
#aisa kya hain constructor ke pass which make him special:
#We write configuration code inside constructor
#ex] as user insert pin (create obj -> in coding language ) we have to connect to database so we can acces balance ,pin and other thing and this thing control
#we cant put into hand of user this is constructor superpower and that's why it executes without any call()
#Kuch chijo ka control user ke haat me nahi dena and kuch chize kam shuru hote hi execute karana iske liye hum constructor banate hain!

# god ,earth, Human



"""## self"""

#self
#1.Instance of class / object of class / gangadhar hi shaktiman hain / objcet inside class = self

# golden rule of programming:
# Methods and data of class is accesible by only and only object of the class

# what if the one method of class needs to call/talk to another method.
# in above ex] constructor calls menu. it uses self beacaz a method can't tal/call another method of class.It is applies on data also

# To solve above problem obj itself goes into class by becoming self
#when we create object of the class, we are indireclty sending that object into class by name of self(you can take nay name ). It is hidden code

obj1=Atm()

#Proving object goes by name of self

obj1.check_balance()

#In above we try to call check_balace method it says "Atm.check_balance() takes 0 positional arguments but 1 was given" but we dont pass any argument"obj1.check_balance()".
#That's i am telling when we create object.It itself goes into class by becoming argment.



#Proving object goes by name of self 2

print(id(self)) # Check below code

"""print(id(obj))"""



"""## How to create own data type"""

class Fraction:
    def __init__(self,x,y): # The constructor which take input known as parameterized constructor
        self.num = x
        self.den = y
        # print(id(self))

    def __str__(self): # Returns a string
        return '{}/{}'.format(self.num,self.den)

    def __add__(self,other):
        new_num = self.num*other.den + other.num*self.den
        new_den = self.den*other.den
        return '{}/{}'.format(new_num,new_den)

    def __sub__(self,other):
        new_num = self.num*other.den - other.num*self.den
        new_den = self.den*other.den
        return '{}/{}'.format(new_num,new_den)

    def __mul__(self,other):
        new_num = self.num*other.num
        new_den = self.den*other.den
        return '{}/{}'.format(new_num,new_den)

    def __truediv__(self,other):
        new_num = self.num*other.den
        new_den = self.den*other.num
        return '{}/{}'.format(new_num,new_den)

    def To_decimal(self):
        return self.num/self.den

obj = Fraction(3,4)

# print(id(obj)) # obj = self

print(obj) # we want 3/4 like this
# when we want to print object python automatically/by default execute __str__(self) block

obj2 = Fraction(1,2)

print(obj2)



(obj + obj2)

(obj - obj2)

(obj * obj2)

(obj / obj2)

obj.To_decimal()

